steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/crawler-images/adult-v-crawler:latest'
      - '-f'
      - 'Dockerfile.crawler'
      - '.'
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/crawler-images/adult-v-crawler:latest'
