steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/crawler:latest',
        '-t',
        'asia-northeast1-docker.pkg.dev/$PROJECT_ID/crawler/crawler:latest',
        '-f',
        'docker/Dockerfile.crawler',
        '.',
      ]
images:
  - 'gcr.io/$PROJECT_ID/crawler:latest'
  - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/crawler/crawler:latest'
